# Generated by Django 4.1.7 on 2023-03-22 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_client_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
